apiVersion: v1
kind: LimitRange
metadata:
  name: pods
  namespace: resourcequotas
spec:
  limits:
    - type: Container
      max:
        cpu: "1"
        memory: 1Gi
      min:
        cpu: "0.5"
        memory: 512Mi
      default:
        cpu: "1"
        memory: 1024Mi
      defaultRequest:
        cpu: "0.5"
        memory: 512Mi
