apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: resourcequotas
spec:
  hard:
    pods: 2
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 4Gi
