apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
    - name: main
      image: alpine:latest
      ports:
        - containerPort: 80
      command:
        - sh
        - -c
        - while true; do echo 'Hello, Kubernetes!'; sleep 10; done
      volumeMounts:
        - name: script
          mountPath: /opt/scripts
  volumes:
    - name: script
      configMap:
        name: error-monitoring
