apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: greeting
  name: greeting
  namespace: configuration
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - |-
          env
          mkdir -p /etc/greeting
          ls -l /etc/greeting
          cat /etc/greeting/HALLO
          cat /etc/greeting/HELLO
      image: alpine
      name: alpine
      resources: {}
      envFrom:
        - configMapRef:
            name: greeting
      volumeMounts:
        - mountPath: /etc/greeting
          name: config-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: config-volume
      configMap:
        name: greeting
status: {}
