apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: "0.25"
        memory: "64Mi"
      limits:
        cpu: "0.5"
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
