apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["sleep", $(sleeping-time)]
    env:
    - name: env1
      value: value1
    envFrom:
      - configMapRef:
          name: busybox-environment
    volumeMounts:
    - name: configuration
      mountPath: /config 
      readOnly: true
    resources:
      requests:
        cpu: "0.25"
        memory: "64Mi"
      limits:
        cpu: "0.5"
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: configuration
    configMap:
      name: busybox-configuration
      items:
      - key: "config.properties"
        path: "config.properties"
      - key: "user.properties"
        path: "user.properties" 
status: {}
